spring:
  application:
    name: realtime-notification-system
  profiles:
    active: dev

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.pcveldi: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-dispatch-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.pcveldi.notification.model
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      group-id: notification-dispatch-group
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
